"""Markdown report of a pipeline run (``artifacts/report.md``)."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd

if TYPE_CHECKING:
    from montecarlo_decisions.pipeline import PipelineResult


def markdown_table(frame: pd.DataFrame) -> str:
    columns = [str(column) for column in frame.columns]
    lines = ["| " + " | ".join(columns) + " |", "|" + "---|" * len(columns)]
    for row in frame.itertuples(index=False):
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return "\n".join(lines)


def _eur(value: float) -> str:
    return f"{value:,.0f}"


def _pct(value: float) -> str:
    return f"{value:.1%}"


def decision_table(summary: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "#": summary["ranking"],
            "decision": summary["label"],
            "E[profit] EUR": summary["expected_profit_eur"].map(_eur),
            "P10": summary["p10_eur"].map(_eur),
            "P50": summary["p50_eur"].map(_eur),
            "P90": summary["p90_eur"].map(_eur),
            "CVaR 5%": summary["cvar_5_eur"].map(_eur),
            "P(loss)": summary["probability_loss"].map(_pct),
            "P(best)": summary["probability_best"].map(_pct),
            "ROI": summary["expected_roi"].map(lambda v: f"{v:.1f}x"),
            "break-even P(fail)": summary["breakeven_failure_probability"].map(_pct),
        }
    )


def uplift_table(uplift: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "lever": uplift["label"],
            "n": uplift["sample_size"],
            "conv. lift (model)": uplift["conversion_lift_pct"].map(_pct),
            "conv. lift (true)": uplift["true_conversion_lift_pct"].map(_pct),
            "value lift EUR (model, 95% CI)": [
                f"{row.value_lift_per_opportunity_eur:.1f} "
                f"[{row.value_lift_ci_low_eur:.1f}, {row.value_lift_ci_high_eur:.1f}]"
                for row in uplift.itertuples()
            ],
            "value lift EUR (true)": uplift["true_value_lift_per_opportunity_eur"].map(
                lambda v: f"{v:.1f}"
            ),
            "value lift EUR (naive, no time control)": uplift[
                "naive_value_lift_per_opportunity_eur"
            ].map(lambda v: f"{v:.1f}"),
        }
    )


def render_report(result: PipelineResult) -> str:
    prepared = result.prepared
    history = prepared.history
    classification = prepared.model_report["classification"]
    regression = prepared.model_report["regression"]
    summary = result.summary
    best = summary.iloc[0]
    checks = "\n".join(
        f"- [{'x' if check.passed else ' '}] **{check.name}**: {check.detail}"
        for check in result.checks
    )
    return f"""# Monte Carlo decision report

Generated by `mcd pipeline`: seed {prepared.seed}, {summary["n_simulations"].iloc[0]:,} simulated
futures per decision, {len(prepared.base):,} opportunities per
{prepared.config.simulation.horizon_months}-month horizon, {prepared.deltas.values.shape[0]}
bootstrap model refits.

Break-even P(fail) is the failure probability at which the expected profit would be zero
(0% when the decision loses money even if it always ships).

## Validation checks

{checks}

## Decision ranking

{markdown_table(decision_table(summary))}

**{best["label"]}** has the highest expected incremental profit
({_eur(best["expected_profit_eur"])} EUR, P(loss) {_pct(best["probability_loss"])}, best option in
{_pct(best["probability_best"])} of futures).

## Counterfactual uplift vs ground truth

{markdown_table(uplift_table(prepared.uplift))}

The naive column reproduces a model without a time control; its bias on levers that were rolled
out over time is the calendar confounding described in `docs/methodology.md`.

## Models

Temporal holdout: {prepared.model_report["split"]["test_period_start"]} to
{prepared.model_report["split"]["test_period_end"]}.

- Conversion (logistic regression): AUC {classification["auc"]:.3f}, Brier
  {classification["brier"]:.4f}, expected calibration error
  {classification["expected_calibration_error"]:.4f}.
- Ticket (gradient boosting on log-ticket, smearing {regression["smearing_factor"]:.3f}): MAE
  {_eur(regression["mae_eur"])} EUR, R² {regression["r2"]:.3f}.

## History

- {len(history):,} opportunities, {history["date"].min()} to {history["date"].max()}.
- Conversion {_pct(history["converted_to_sale"].mean())}, revenue
  {_eur(history["revenue_eur"].sum())} EUR, contribution profit
  {_eur(history["contribution_profit_eur"].sum())} EUR.
"""


def write_report(result: PipelineResult, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report(result), encoding="utf-8")
